name: Module Grading

on:
  workflow_call:
    inputs:
        module-name:
          required: true
          type: string
          default: ''
        
        module-id:
          required: true
          type: string
          default: ''

jobs:
  build:
    name: Task Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout repo with tests
        uses: actions/checkout@master
        with:
          repository: linerotechab/kotlin-hw-results
          token: ${{ secrets.my_pat }}
          path: ./kotlin-hw-results

      - name: Move test files to local repository
        run: |
          cp -r ./kotlin-hw-results/src/test/kotlin/helper ./src/test/kotlin
          cp -r ./kotlin-hw-results/src/test/kotlin/${{ inputs.module-id }} ./src/test/kotlin
          gradle --version

      - name: Delete all non-graded modules
        run: |
          cd src/main/kotlin
          rm -r $(ls -A | grep -v ${{ inputs.module-id }})

      - name: Test Module
        run: gradle test --tests "${{ inputs.module-id }}.*"

      - name: Retrieve Badge Title
        if: always()
        run: |
          if [ -f "$PWD/badge.txt" ];
          then
          
          echo "badgeTitle=$(head -n 1 $PWD/badge.txt)" >> $GITHUB_ENV
          else
          
          echo "badgeTitle=0" >> $GITHUB_ENV
          fi

      - name: Retrieve Badge Color
        if: always()
        run: |
          if [ -f "$PWD/badge.txt" ];
          then

          echo "badgeColor=$(tail -n 1 $PWD/badge.txt )" >> $GITHUB_ENV
          else
          
          echo "badgeColor=D53644" >> $GITHUB_ENV
          fi

      - name: Create Badge
        if: always()
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: ${{ inputs.module-id }}
          LABEL: ${{ inputs.module-name }}
          ICON: 'github'
          STATUS: ${{ env.badgeTitle }}% Completed
          COLOR: ${{ env.badgeColor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
